// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import MultiPlatformLibrary

/**
 * selector: ClassContext/dev.icerock.moko:shared/dev/icerock/moko/fields/sample/declarativeui/LoginViewModel.Action */
public enum LoginViewModelActionKs {

  case showMessage(LoginViewModelActionShowMessage)

  public init(_ obj: LoginViewModelAction) {
    if let obj = obj as? MultiPlatformLibrary.LoginViewModelActionShowMessage {
      self = .showMessage(obj)
    } else {
      fatalError("LoginViewModelActionKs not syncronized with LoginViewModelAction class")
    }
  }

}
