// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import Foundation
import MultiPlatformLibrary
import UIKit

public extension UIKit.UITextField {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextField)/bindTextTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/String)>
   */
  @discardableResult
  public func bindTextTwoWay(liveData: MutableLiveData<NSString>) -> Closeable {
    return UITextFieldBindingsKt.bindTextTwoWay(self, liveData: liveData)
  }
}
