// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import Foundation
import MultiPlatformLibrary
import UIKit

public extension Foundation.Bundle {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.utils/Class(name=platform/Foundation/NSBundle.Companion)/loadableBundle/identifier:Class(name=kotlin/String)
   */
  @discardableResult
  public class func loadableBundle(identifier: String) -> Bundle {
    return NSBundleExtKt.loadableBundle(self, identifier: identifier)
  }
}

public extension Swift.String {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.desc/Class(name=kotlin/String)/desc/
   */
  @discardableResult
  public func desc() -> RawStringDesc {
    return StringDescKt.desc(self)
  }
}

public extension MultiPlatformLibrary.StringDesc {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.desc/Class(name=dev/icerock/moko/resources/desc/StringDesc)/plus/other:Class(name=dev/icerock/moko/resources/desc/StringDesc)
   */
  @discardableResult
  public func plus(other: StringDesc) -> StringDesc {
    return StringDescKt.plus(self, other: other)
  }
}

public extension MultiPlatformLibrary.Color {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.desc.color/Class(name=dev/icerock/moko/graphics/Color)/asColorDesc/
   */
  @discardableResult
  public func asColorDesc() -> ColorDesc {
    return ColorDescSingleKt.asColorDesc(self)
  }
}

public extension MultiPlatformLibrary.ColorDesc {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.desc.color/Class(name=dev/icerock/moko/resources/desc/color/ColorDesc)/getUIColor/
   */
  @discardableResult
  public func getUIColor() -> UIColor {
    return ColorDescExtKt.getUIColor(self)
  }
}

public extension Swift.String {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:resources/dev.icerock.moko.resources.desc.image/Class(name=kotlin/String)/asImageUrl/
   */
  @discardableResult
  public func asImageUrl() -> ImageDesc {
    return ImageDescUrlKt.asImageUrl(self)
  }
}
