// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import Foundation
import MultiPlatformLibrary
import UIKit

public extension UIKit.UIView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIView)/bindBackgroundColor/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>,trueColor:Class(name=platform/UIKit/UIColor),falseColor:Class(name=platform/UIKit/UIColor)
   */
  @discardableResult
  public func bindBackgroundColor(
    liveData: LiveData<KotlinBoolean>,
    trueColor: UIColor,
    falseColor: UIColor
  ) -> Closeable {
    return UIViewBindingsKt.bindBackgroundColor(self, liveData: liveData, trueColor: trueColor, falseColor: falseColor)
  }
}

public extension UIKit.UIControl {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIControl)/bindEnabled/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindEnabled(liveData: LiveData<KotlinBoolean>) -> Closeable {
    return UIControlBindingsKt.bindEnabled(self, liveData: liveData)
  }
}

public extension UIKit.UIView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIView)/bindFocus/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindFocus(liveData: LiveData<KotlinBoolean>) -> Closeable {
    return UIViewBindingsKt.bindFocus(self, liveData: liveData)
  }
}

public extension UIKit.UIControl {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIControl)/bindFocusTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindFocusTwoWay(liveData: MutableLiveData<KotlinBoolean>) -> Closeable {
    return UIControlBindingsKt.bindFocusTwoWay(self, liveData: liveData)
  }
}

public extension UIKit.UITextView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextView)/bindFocusTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindFocusTwoWay(liveData: MutableLiveData<KotlinBoolean>) -> Closeable {
    return UITextViewBindingsKt.bindFocusTwoWay(self, liveData: liveData)
  }
}

public extension UIKit.UIView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIView)/bindHidden/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindHidden(liveData: LiveData<KotlinBoolean>) -> Closeable {
    return UIViewBindingsKt.bindHidden(self, liveData: liveData)
  }
}

public extension UIKit.UIButton {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIButton)/bindImage/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>,trueImage:Class(name=platform/UIKit/UIImage),falseImage:Class(name=platform/UIKit/UIImage)
   */
  @discardableResult
  public func bindImage(
    liveData: LiveData<KotlinBoolean>,
    trueImage: UIImage,
    falseImage: UIImage
  ) -> Closeable {
    return UIButtonBindingsKt.bindImage(self, liveData: liveData, trueImage: trueImage, falseImage: falseImage)
  }
}

public extension UIKit.UISwitch {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UISwitch)/bindSwitchOn/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindSwitchOn(liveData: LiveData<KotlinBoolean>) -> Closeable {
    return UISwitchBindingsKt.bindSwitchOn(self, liveData: liveData)
  }
}

public extension UIKit.UISwitch {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UISwitch)/bindSwitchOnTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/Boolean)>
   */
  @discardableResult
  public func bindSwitchOnTwoWay(liveData: MutableLiveData<KotlinBoolean>) -> Closeable {
    return UISwitchBindingsKt.bindSwitchOnTwoWay(self, liveData: liveData)
  }
}

public extension UIKit.UILabel {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UILabel)/bindText/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<TypeParameter(id=0)>
   */
  @discardableResult
  public func bindText<T : NSString>(liveData: LiveData<T>) -> Closeable {
    return UILabelBindingsKt.bindText(self, liveData: liveData as! MultiPlatformLibrary.LiveData<Foundation.NSString>)
  }
}

public extension UIKit.UITextField {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextField)/bindText/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<TypeParameter(id=0)>
   */
  @discardableResult
  public func bindText<T : NSString>(liveData: LiveData<T>) -> Closeable {
    return UITextFieldBindingsKt.bindText(self, liveData: liveData as! MultiPlatformLibrary.LiveData<Foundation.NSString>)
  }
}

public extension UIKit.UITextView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextView)/bindText/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<TypeParameter(id=0)>
   */
  @discardableResult
  public func bindText<T : NSString>(liveData: LiveData<T>) -> Closeable {
    return UITextViewBindingsKt.bindText(self, liveData: liveData as! MultiPlatformLibrary.LiveData<Foundation.NSString>)
  }
}

public extension UIKit.UITextField {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextField)/bindTextTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/String)>
   */
  @discardableResult
  public func bindTextTwoWay(liveData: MutableLiveData<NSString>) -> Closeable {
    return UITextFieldBindingsKt.bindTextTwoWay(self, liveData: liveData)
  }
}

public extension UIKit.UITextView {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UITextView)/bindTextTwoWay/liveData:Class(name=dev/icerock/moko/mvvm/livedata/MutableLiveData)<Class(name=kotlin/String)>
   */
  @discardableResult
  public func bindTextTwoWay(liveData: MutableLiveData<NSString>) -> Closeable {
    return UITextViewBindingsKt.bindTextTwoWay(self, liveData: liveData)
  }
}

public extension UIKit.UIButton {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata/dev.icerock.moko.mvvm.livedata/Class(name=platform/UIKit/UIButton)/bindTitle/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<TypeParameter(id=0)>
   */
  @discardableResult
  public func bindTitle<T : NSString>(liveData: LiveData<T>) -> Closeable {
    return UIButtonBindingsKt.bindTitle(self, liveData: liveData as! MultiPlatformLibrary.LiveData<Foundation.NSString>)
  }
}
