// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import MultiPlatformLibrary
import UIKit

public extension UIKit.UILabel {
  /**
   * selector: PackageFunctionContext/dev.icerock.moko:mvvm-livedata-resources/dev.icerock.moko.mvvm.livedata.resources/Class(name=platform/UIKit/UILabel)/bindText/liveData:Class(name=dev/icerock/moko/mvvm/livedata/LiveData)<TypeParameter(id=0)>
   */
  @discardableResult
  public func bindText<T : StringDesc>(liveData: LiveData<T>) -> Closeable {
    return UILabelBindingKt.bindText(self, liveData: liveData as! MultiPlatformLibrary.LiveData<MultiPlatformLibrary.StringDesc>)
  }
}
