// This file automatically generated by MOKO KSwift (https://github.com/icerockdev/moko-kswift)
//
import Foundation
import MultiPlatformLibrary

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/async/context:Class(name=kotlin/coroutines/CoroutineContext),start:Class(name=kotlinx/coroutines/CoroutineStart),block:Class(name=kotlin/Function2)<Class(name=kotlinx/coroutines/CoroutineScope),Class(name=kotlin/coroutines/Continuation)<TypeParameter(id=0)>,Class(name=kotlin/Any)>
   */
  @discardableResult
  public func async<T>(
    context: CoroutineContext,
    start: CoroutineStart,
    block: Function2<CoroutineScope, Continuation<T>, AnyObject>
  ) -> Deferred<T> {
    return Builders.commonKt.async(self, context: context, start: start, block: block)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancel/
   */
  @discardableResult
  public func cancel() {
    return JobKt.cancel(self)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancel/cause:Class(name=kotlin/Throwable)
   */
  @discardableResult
  public func cancel(cause: KotlinThrowable) -> Bool {
    return JobKt.cancel(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancel/cause:Class(name=kotlin/coroutines/cancellation/CancellationException)
   */
  @discardableResult
  public func cancel(cause: CancellationException) {
    return JobKt.cancel(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/cancel/message:Class(name=kotlin/String),cause:Class(name=kotlin/Throwable)
   */
  @discardableResult
  public func cancel(message: String, cause: KotlinThrowable) {
    return CoroutineScopeKt.cancel(self, message: message, cause: cause)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/cancel/cause:Class(name=kotlin/coroutines/cancellation/CancellationException)
   */
  @discardableResult
  public func cancel(cause: CancellationException) {
    return CoroutineScopeKt.cancel(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/cancel/message:Class(name=kotlin/String),cause:Class(name=kotlin/Throwable)
   */
  @discardableResult
  public func cancel(message: String, cause: KotlinThrowable) {
    return JobKt.cancel(self, message: message, cause: cause)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/cancelAndJoin/
   */
  @discardableResult
  public func cancelAndJoin() {
    return JobKt.cancelAndJoin(self)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancelChildren/
   */
  @discardableResult
  public func cancelChildren() {
    return JobKt.cancelChildren(self)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancelChildren/cause:Class(name=kotlin/Throwable)
   */
  @discardableResult
  public func cancelChildren(cause: KotlinThrowable) {
    return JobKt.cancelChildren(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/cancelChildren/cause:Class(name=kotlin/coroutines/cancellation/CancellationException)
   */
  @discardableResult
  public func cancelChildren(cause: CancellationException) {
    return JobKt.cancelChildren(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/cancelChildren/
   */
  @discardableResult
  public func cancelChildren() {
    return JobKt.cancelChildren(self)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/cancelChildren/cause:Class(name=kotlin/Throwable)
   */
  @discardableResult
  public func cancelChildren(cause: KotlinThrowable) {
    return JobKt.cancelChildren(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/cancelChildren/cause:Class(name=kotlin/coroutines/cancellation/CancellationException)
   */
  @discardableResult
  public func cancelChildren(cause: CancellationException) {
    return JobKt.cancelChildren(self, cause: cause)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/ensureActive/
   */
  @discardableResult
  public func ensureActive() {
    return JobKt.ensureActive(self)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/ensureActive/
   */
  @discardableResult
  public func ensureActive() {
    return CoroutineScopeKt.ensureActive(self)
  }
}

public extension MultiPlatformLibrary.Job {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/Job)/ensureActive/
   */
  @discardableResult
  public func ensureActive() {
    return JobKt.ensureActive(self)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/launch/context:Class(name=kotlin/coroutines/CoroutineContext),start:Class(name=kotlinx/coroutines/CoroutineStart),block:Class(name=kotlin/Function2)<Class(name=kotlinx/coroutines/CoroutineScope),Class(name=kotlin/coroutines/Continuation)<Class(name=kotlin/Unit)>,Class(name=kotlin/Any)>
   */
  @discardableResult
  public func launch(
    context: CoroutineContext,
    start: CoroutineStart,
    block: Function2<CoroutineScope, Continuation<Void>, AnyObject>
  ) -> Job {
    return Builders.commonKt.launch(self, context: context, start: start, block: block)
  }
}

public extension MultiPlatformLibrary.CoroutineContext {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlin/coroutines/CoroutineContext)/newCoroutineContext/addedContext:Class(name=kotlin/coroutines/CoroutineContext)
   */
  @discardableResult
  public func newCoroutineContext(addedContext: CoroutineContext) -> CoroutineContext {
    return CoroutineContextKt.newCoroutineContext(self, addedContext: addedContext)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/newCoroutineContext/context:Class(name=kotlin/coroutines/CoroutineContext)
   */
  @discardableResult
  public func newCoroutineContext(context: CoroutineContext) -> CoroutineContext {
    return CoroutineContextKt.newCoroutineContext(self, context: context)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines/Class(name=kotlinx/coroutines/CoroutineScope)/plus/context:Class(name=kotlin/coroutines/CoroutineContext)
   */
  @discardableResult
  public func plus(context: CoroutineContext) -> CoroutineScope {
    return CoroutineScopeKt.plus(self, context: context)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.channels/Class(name=kotlinx/coroutines/CoroutineScope)/broadcast/context:Class(name=kotlin/coroutines/CoroutineContext),capacity:Class(name=kotlin/Int),start:Class(name=kotlinx/coroutines/CoroutineStart),onCompletion:Class(name=kotlin/Function1)<Class(name=kotlin/Throwable),Class(name=kotlin/Unit)>,block:Class(name=kotlin/Function2)<Class(name=kotlinx/coroutines/channels/ProducerScope)<TypeParameter(id=0)>,Class(name=kotlin/coroutines/Continuation)<Class(name=kotlin/Unit)>,Class(name=kotlin/Any)>
   */
  @discardableResult
  public func broadcast<E>(
    context: CoroutineContext,
    capacity: NSNumber,
    start: CoroutineStart,
    onCompletion: @escaping (KotlinThrowable) -> Void,
    block: Function2<ProducerScope<E>, Continuation<Void>, AnyObject>
  ) -> BroadcastChannel<E> {
    return BroadcastKt.broadcast(self, context: context, capacity: capacity, start: start, onCompletion: onCompletion, block: block)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.channels/Class(name=kotlinx/coroutines/CoroutineScope)/produce/context:Class(name=kotlin/coroutines/CoroutineContext),capacity:Class(name=kotlin/Int),start:Class(name=kotlinx/coroutines/CoroutineStart),onCompletion:Class(name=kotlin/Function1)<Class(name=kotlin/Throwable),Class(name=kotlin/Unit)>,block:Class(name=kotlin/Function2)<Class(name=kotlinx/coroutines/channels/ProducerScope)<TypeParameter(id=0)>,Class(name=kotlin/coroutines/Continuation)<Class(name=kotlin/Unit)>,Class(name=kotlin/Any)>
   */
  @discardableResult
  public func produce<E>(
    context: CoroutineContext,
    capacity: NSNumber,
    start: CoroutineStart,
    onCompletion: @escaping (KotlinThrowable) -> Void,
    block: Function2<ProducerScope<E>, Continuation<Void>, AnyObject>
  ) -> ReceiveChannel<E> {
    return ProduceKt.produce(self, context: context, capacity: capacity, start: start, onCompletion: onCompletion, block: block)
  }
}

public extension MultiPlatformLibrary.CoroutineScope {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.channels/Class(name=kotlinx/coroutines/CoroutineScope)/produce/context:Class(name=kotlin/coroutines/CoroutineContext),capacity:Class(name=kotlin/Int),block:Class(name=kotlin/Function2)<Class(name=kotlinx/coroutines/channels/ProducerScope)<TypeParameter(id=0)>,Class(name=kotlin/coroutines/Continuation)<Class(name=kotlin/Unit)>,Class(name=kotlin/Any)>
   */
  @discardableResult
  public func produce<E>(
    context: CoroutineContext,
    capacity: NSNumber,
    block: Function2<ProducerScope<E>, Continuation<Void>, AnyObject>
  ) -> ReceiveChannel<E> {
    return ProduceKt.produce(self, context: context, capacity: capacity, block: block)
  }
}

public extension MultiPlatformLibrary.KotlinArray {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.flow/Class(name=kotlin/Array)/asFlow/
   */
  @discardableResult
  public func asFlow<T>() -> Flow<T> {
    return BuildersKt.asFlow(self)
  }
}

public extension MultiPlatformLibrary.KotlinIntArray {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.flow/Class(name=kotlin/IntArray)/asFlow/
   */
  @discardableResult
  public func asFlow() -> Flow<NSNumber> {
    return BuildersKt.asFlow(self)
  }
}

public extension MultiPlatformLibrary.KotlinLongArray {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.flow/Class(name=kotlin/LongArray)/asFlow/
   */
  @discardableResult
  public func asFlow() -> Flow<KotlinLong> {
    return BuildersKt.asFlow(self)
  }
}

public extension MultiPlatformLibrary.IntRange {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.flow/Class(name=kotlin/ranges/IntRange)/asFlow/
   */
  @discardableResult
  public func asFlow() -> Flow<NSNumber> {
    return BuildersKt.asFlow(self)
  }
}

public extension MultiPlatformLibrary.LongRange {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.flow/Class(name=kotlin/ranges/LongRange)/asFlow/
   */
  @discardableResult
  public func asFlow() -> Flow<KotlinLong> {
    return BuildersKt.asFlow(self)
  }
}

public extension MultiPlatformLibrary.Mutex {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.sync/Class(name=kotlinx/coroutines/sync/Mutex)/withLock/owner:Class(name=kotlin/Any),action:Class(name=kotlin/Function0)<TypeParameter(id=0)>
   */
  @discardableResult
  public func withLock<T>(owner: AnyObject, action: Function0<T>) -> T {
    return MutexKt.withLock(self, owner: owner, action: action as! MultiPlatformLibrary.Function0<Swift.AnyObject>)
  }
}

public extension MultiPlatformLibrary.Semaphore {
  /**
   * selector: PackageFunctionContext/org.jetbrains.kotlinx:kotlinx-coroutines-core/kotlinx.coroutines.sync/Class(name=kotlinx/coroutines/sync/Semaphore)/withPermit/action:Class(name=kotlin/Function0)<TypeParameter(id=0)>
   */
  @discardableResult
  public func withPermit<T>(action: Function0<T>) -> T {
    return SemaphoreKt.withPermit(self, action: action as! MultiPlatformLibrary.Function0<Swift.AnyObject>)
  }
}
